### ISSUE TITLE
Ruszenie z kopyta

### ISSUE THREAD

**Issue by ZielonyBuszmen** [Sikora00/jewish-app-web-client#3]
Witojcie!
No, projekt już leży jakiś czas, mało się tu dzieje, a każdy chciałby zakodzić. Moim zdaniem stagnację powoduje brak konkretnych celów.

Otóż proponuję, by nasz Product Owner @MaciejSikorski stworzył jakąś strukturę komponentów, dał pomysł na wygląd aplikacji, stworzył parę prostych makiet w Paincie i opisał trochę lepiej taski na trello. Myślę, że wówczas praca mogłaby "ruszyć z kopyta", bo wiadomo by było co trzeba zrobić :smiley:

**Comment by MaciejSikorski** [comment]
Masz rację, czekamy na mockupy od Eweliny i trochę za bardzo na tym się skupiliśmy zamiast zacząć działać. A co myślisz żeby jednak robić issues na githubie zamiast trello?

**Comment by ZielonyBuszmen** [comment]
Ciekawy pomysł z tworzeniem issues na GitHubie. Wówczas wszystko jest w jednym miejscu (Github, powiadomienia), nie trzeba przełączać się na Trello i szukać odpowiedniej tablicy (co może na starcie zniechęcać np. mnie :wink:). Dodatkowo GitHub ma takie coś jak "Projects" - przetestuj jak to działa, może być to strzałem w dziesiątkę
